common:
  app:
    name: MOKUMOKU
    url: http://localhost.com/
    description: もくもくを募集したり共有するサイトです
    og:
      image: sample.jpg
  password:
    minimum_count: 6
  avatar:
    default_file_name: sample.jpg
    by_sns_file_name: profile_image

twitter:
  account_name: MOKUMOK63955523
  auto_fill_password_count: 8
  share_url: https://twitter.com/intent/tweet

favorite_areas:
  minimum_count: 1
