common:
  app:
    name: MOKUMOKU
    og:
      title: MOKUMOKU
      type: website
      url: https://t-mokumoku-arte.herokuapp.com
      image: site_image.jpg
      site_name: MOKUMOKU
      description: 孤独なプログラミングとはおさらば！気軽にプログラミング仲間を探せるサービス登場！
  password:
    minimum_count: 6
  avatar:
    default_file_name: sample.jpg
    by_sns_file_name: profile_image

twitter:
  account_name: MOKUMOK63955523
  share_url: https://twitter.com/intent/tweet
  card: summary_large_image
  auto_fill_password_count: 8

favorite_areas:
  minimum_count: 1
